version: "3"
services:
  authors:
    build: ./authors
    container_name: authors-service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    volumes:
      - ${PWD}/authors/authors-service.log:/var/www/node/authors-service.log
    ports:
      - 8081:8081
    depends_on:
      - redis
      - jaeger
    networks:
      - mynet

  books:
    build: ./books
    container_name: books-service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    volumes:
      - ${PWD}/books/books-service.log:/var/www/node/books-service.log
    ports:
      - 8082:8082
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger

  frontend:
    build: ./frontend
    container_name: frontend-service
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    volumes:
      - ${PWD}/frontend/frontend-service.log:/var/www/node/frontend-service.log
    ports:
      - 8083:8083
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mynet

  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    container_name: jaeger
    ports:
      - 16686:16686
      - 6832:6832/udp
    networks:
      - mynet

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mynet

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.2.0"
    ports:
      - "5601:5601"
    networks:
      - mynet

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    volumes:
      - ${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${PWD}/authors/authors-service.log:/var/log/authors-service.log
      - ${PWD}/books/books-service.log:/var/log/books-service.log
      - ${PWD}/frontend/frontend-service.log:/var/log/frontend-service.log
    networks:
      - mynet

  prometheus:
    image: "prom/prometheus:v2.20.1"
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mynet

  grafana:
    image: "grafana/grafana:7.1.5"
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - mynet

networks:
  mynet:

volumes:
  elasticsearch_data:
